name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login the Docker image
      env:
        tag: ${{ github.sha }}
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      env:
        tag: ${{ github.sha }}
      run: docker build . --file Dockerfile --tag appium:$tag
    - name: Push the Docker image
      env:
        tag: ${{ github.sha }}
      run: docker push appium:$tag
